project:
  type: website
  output-dir: docs

website:
  title: "website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Experiments
        href: experimenting.qmd

format:
  
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
  
  

editor: visual

